### ISSUE TITLE
Commands in quotes can be accepted

### ISSUE THREAD

**Issue by Shinobu1337** [Shinobu1337/discord-command-parser#4]
The command
```
!ping
```
Works, but the command
```
!"ping"
```
Also works, (see index.js, L61) because `getArgs()` and subsequently `RE_ARG_MATCHER` is used. 

TODO: Make a new Regexp for matching just `a-z, A-Z, 0-9, $, _, -`.
and use this for the command.

**Comment by ThePythonDoge** [comment]
Great.

**Comment by Shinobu1337** [comment]
@ThePythonDoge are you in my Discord server?

**Comment by Shinobu1337** [comment]
On second thought, the expression should only match `a-z`, `A-Z`, and `0-9`. Because `$`, `-`, and `_` are all common prefixes, and could be confused easily.

**Comment by Shinobu1337** [comment]
This seems to work.
```js
/^[a-z0-9]+/ig
```
https://regex101.com/r/ybRXwy/1

Will be adding this soon.

**Comment by Shinobu1337** [comment]
https://github.com/Shinobu1337/discord-command-parser/commit/4cc77111b581d840c126ea80507105d3b2614aab
